# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{knife-rackspace}
  s.version = "0.5.12"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["adam@opscode.com", "schisamo@opscode.com"]
  s.date = %q{2011-08-16}
  s.description = %q{This is the official Opscode Knife plugin for Rackspace. This plugin gives knife the ability to create, bootstrap, and manage servers on the Rackspace Cloud.}
  s.email = ["Adam Jacob", "Seth Chisamore"]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "README.md",
    "Rakefile",
    "knife-rackspace.gemspec",
    "lib/chef/knife/rackspace_base.rb",
    "lib/chef/knife/rackspace_flavor_list.rb",
    "lib/chef/knife/rackspace_image_list.rb",
    "lib/chef/knife/rackspace_server_create.rb",
    "lib/chef/knife/rackspace_server_delete.rb",
    "lib/chef/knife/rackspace_server_list.rb",
    "lib/knife-rackspace/version.rb"
  ]
  s.homepage = %q{http://wiki.opscode.com/display/chef}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.9.2}
  s.summary = %q{Rackspace Support for Chef's Knife Command}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<knife-rackspace>, [">= 0"])
      s.add_runtime_dependency(%q<fog>, [">= 0.8.2"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<yard>, [">= 0"])
    else
      s.add_dependency(%q<knife-rackspace>, [">= 0"])
      s.add_dependency(%q<fog>, [">= 0.8.2"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<yard>, [">= 0"])
    end
  else
    s.add_dependency(%q<knife-rackspace>, [">= 0"])
    s.add_dependency(%q<fog>, [">= 0.8.2"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<yard>, [">= 0"])
  end
end

